- Services:
    - TrueNAS:
        icon: truenas.png
        href: http://ip-address
        widget:
          type: truenas
          url: http://ip-address
          username: user # not required if using api key
          password: pass # not required if using api key
          key: yourkeyhereyourkeyhereyourkeyhereyourkeyhere # not required if using username / password
          enablePools: true # optional, defaults to false
          nasType: scale # defaults to scale, must be set to 'core' if using enablePools with TrueNAS Core

    - Immich:
        icon: immich.png
        href: http://ip-address:port
        widget:
          type: immich
          url: http://ip-address:port
          key: yourkeyhereyourkeyhereyourkeyhereyourkeyhere
          version: 2

    - Nextcloud:
        icon: nextcloud.png
        href: http://ip-address:port
        widget:
          type: nextcloud
          url: http://ip-address:port
          username: your-username
          password: your-password

    - Home Assistant:
        icon: home-assistant.png
        href: http://ip-address:port

- Calendar:
    - Calendar:
        widget:
          type: calendar
          firstDayInWeek: sunday # optional - defaults to monday
          view: monthly # optional - possible values monthly, agenda
          maxEvents: 10 # optional - defaults to 10
          showTime: true # optional - show time for event happening today - defaults to false
          timezone: America/Denver # optional and only when timezone is not detected properly (slightly slower performance) - force timezone for ical events (if it's the same - no change, if missing or differe>          integrations: # optional
            - type: ical # Show calendar events from another service
              url: urlurlurlurlurlurlurlurlurl # URL with calendar events
              name: My Events # required - name for these calendar events
              color: teal # optional - defaults to pre-defined color for the service (zinc for ical)
              params: # optional - additional params for the service
                showName: false # optional - show name before event title in event line - defaults to false
            - type: ical # Show calendar events from another service
              url: urlurlurlurlurlurlurlurlurl # URL with calendar events
              name: Birthdays # required - name for these calendar events
              color: yellow # optional - defaults to pre-defined color for the service (zinc for ical
              params: # optional - additional params for the service
                showName: false # optional - show name before event title in event line - defaults to false
            - type: ical # Show calendar events from another service
              url: urlurlurlurlurlurlurlurlurl # URL with calendar events
              name: Holidays # required - name for these calendar events
              color: yellow # optional - defaults to pre-defined color for the service (zinc for ical)
              params: # optional - additional params for the service
                showName: false # optional - show name before event title in event line - defaults to false
