- Services:
    - TrueNAS:
        id: truenas-scale
        icon: truenas-scale.png
        href: http://ip-address
        siteMonitor: http://ip-address
        statusStyle: dot
        widget:
          type: truenas
          fields: ["uptime", "alerts"]
          url: http://ip-address
          key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx # not required if using username / password
          enablePools: true # optional, defaults to false
          nasType: scale # defaults to scale, must be set to 'core' if using enablePools with TrueNAS Core
    - Immich:
        icon: immich.png
        href: http://ip-address:port
        siteMonitor: http://ip-address:port
        statusStyle: dot
        widget:
          type: immich
          fields: ["photos", "videos", "storage"]
          url: http://ip-address:port
          key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
          version: 2
    - Nextcloud:
        icon: nextcloud.png
        href: http://ip-address:port
        siteMonitor: http://ip-address:port
        statusStyle: dot
        widget:
          type: nextcloud
          fields: ["numfiles"]
          url: http://ip-address:port
          username: user
          password: pass
    - Home Assistant:
        icon: home-assistant-light.png
        href: http://ip-address:port
        siteMonitor: http://ip-address:port
        statusStyle: dot
    - Portainer:
        icon: portainer-alt.png
        href: https://ip-address:port
        siteMonitor: https://ip-address:port
        statusStyle: dot
        widget:
          type: portainer
          url: https://ip-address:port
          env: 3
          key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    - Tailscale:
        icon: tailscale-light.png
        href: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        widget:
          type: tailscale
          deviceid: xxxxxxxxxxx
          key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    - NetAlertX:
        icon: netalertx.png
        id: netalert
        href: http://ip-address:port
        siteMonitor: http://ip-address:port
        statusStyle: dot
        widget:
          type: netalertx
          url: http://ip-address:port
    - Glances:
        icon: glances.png
        href: http://ip-address:port
        siteMonitor: http://ip-address:port
        statusStyle: dot
        
- Graphs:
    - CPU:
        widget:
          type: glances
          url: http://ip-address:port
          metric: cpu
          version: 4
    - CPU Temp:
        widget:
          type: glances
          url: http://ip-address:port
          metric: sensor:Package id 0
          version: 4
    - RAM:
        widget:
          type: glances
          url: http://ip-address:port
          metric: memory
          version: 4
    - Network:
        widget:
          type: glances
          url: http://ip-address:port
          metric: network:eth0
          version: 4
    - Boot Drive:
        widget:
          type: glances
          url: http://ip-address:port
          metric: disk:sdb
          version: 4
    - Mirrored Drive 1:
        widget:
          type: glances
          url: http://ip-address:port
          metric: disk:sdc
          version: 4
    - Mirrored Drive 2:
        widget:
          type: glances
          url: http://ip-address:port
          metric: disk:sda
          version: 4

- iframes:
    - Tasks:
        widget:
          type: iframe
          name: Tasks
          src: https://app.todoist.com
          classes: h-96 # optional, use tailwind height classes, see https://tailwindcss.com/docs/height
          referrerPolicy: same-origin # optional, no default
          allowPolicy: fullscreen # optional, no default
          allowFullscreen: false # optional, default: true
          loadingStrategy: eager # optional, default: eager
          allowScrolling: no # optional, default: yes
    - Calendar:
        widget:
          type: calendar
          firstDayInWeek: sunday # optional - defaults to monday
          view: monthly # optional - possible values monthly, agenda
          maxEvents: 50 # optional - defaults to 10
          showTime: true # optional - show time for event happening today - defaults to false
          timezone: Country/City # optional and only when timezone is not detected properly (slightly slower performance) - force timezone for ical events (if it's the same - no change, if missing or differe>    - ADS-B Exchange:
        widget:
          type: iframe
          name: ADS-B Exchange
          src: https://globe.adsbexchange.com/
          classes: h-96 # optional, use tailwind height classes, see https://tailwindcss.com/docs/height
          referrerPolicy: same-origin # optional, no default
          allowPolicy: fullscreen # optional, no default
          allowFullscreen: false # optional, default: true
          loadingStrategy: eager # optional, default: eager
          allowScrolling: no # optional, default: yes
